backend:
  name: git-gateway
  branch: next
  accept_roles:
    - admin
    - editor
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "introduction"
    label: "[Page] Introduction"
    description: "The introduction page of Euromat."
    folder: "src/app/intro/content"
    format: "json"
    create: true
    identifier_field: language
    slug: "{{slug}}-{{title}}"
    fields:
      - label: "Language"
        name: "language"
        widget: "select"
        options:
          - {label: "English", value: "en"}
          - {label: "Deutsch", value: "de"}
          - {label: "Français", value: "fr"}
          - {label: "Polski", value: "pl"}
      - label: "Site Name"
        name: "title"
        widget: "string"
      - label: "Headline"
        name: "headline"
        widget: "string"
      - label: "Content"
        name: "content"
        widget: "markdown"
      - label: "Button Label"
        name: "button"
        widget: "string"
  - name: "setup"
    label: "Setup"
    files:
    - label: "Site Info"
      name: "info"
      format: 'json'
      file: "src/data/setup/info.json"
      fields:
        - {label: Site Name, name: sitename, widget: string}
        - {label: Site Description, name: sitedescription, widget: string}
    - label: "Social Media"
      name: "connect"
      format: 'json'
      file: "src/data/setup/socialmedia.json"
      fields:
        - label: 'Links'
          name: 'socialMedia'
          widget: 'list'
          fields:
            - {label: Link Name, name: name, widget: string}
            - {label: URL, name: url, widget: string}
