backend:
  name: git-gateway
  branch: next
  accept_roles:
    - admin
    - editor
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - label: "Setup"
    name: "setup"
    files:
    - label: "Site Info"
      name: "info"
      format: 'json'
      file: "src/data/setup/info.json"
      fields:
        - {label: Site Name, name: sitename, widget: string}
        - {label: Site Description, name: sitedescription, widget: string}
    - label: "Social Media"
      name: "connect"
      format: 'json'
      file: "src/data/setup/socialmedia.json"
      fields:
        - label: 'Links'
          name: 'socialMedia'
          widget: 'list'
          fields:
            - {label: Link Name, name: name, widget: string}
            - {label: URL, name: url, widget: string}
